/*
Company : Arcus Global
Product : Arcus Integration Architecture
Purpose : Config settings manager for ALL CUSTOM api integrations
Notes :
 */
public with sharing class ArcI_UtilityConfigCUSTOM
{
    /************************** START FHDC MyArea Settings****************************************************************/
    /***************************************************************************************************************************/
    public static final String MY_AREA_API_KEY = 'aCvA0YQ6Zs';
    
    //named credentials
    public static final String MY_AREA_API_ENDPOINT_NAMEDCREDS_TEST = 'MyAreaApi_Test';
    public static final String MY_AREA_API_ENDPOINT_NAMEDCREDS_LIVE = 'MyAreaApi_Live';
    /***************************************************************************************************************************/
    /************************** END FHDC MyArea Settings******************************************************************/


    // public static void insertCustomSettings()
    // {
    //     /********* ADD custom settings here that need inserting **********/
    // }
}