/*
Company : Arcus Global
Product : Arcus Integration Architecture
Purpose : Config settings manager for various webservice integrations that form that unlocked integrations package
Notes :
 */
public with sharing class ArcI_UtilityConfigSettings
{
    /************************** START Mod.gov Settings****************************************************************/
    /***************************************************************************************************************************/
    public static final String CALL_OUT_MODGOV_WEBSERVICES_ENDPOINT_NAMEDCREDS_TEST = 'ModGov_Test';
    public static final String CALL_OUT_MODGOV_WEBSERVICES_ENDPOINT_NAMEDCREDS_LIVE = 'ModGov_Live';
    /***************************************************************************************************************************/
    /************************** END Mod.gov Settings******************************************************************/


	// public static void insertCustomSettings()
	// {
	// 	//add any custom setting here that need inserting
	// }
}