@isTest
public class CaseStaffHubApexSharing_Test {

    @TestSetup
    static void setup(){
        
        
        
        
    }

    @isTest
    private static void testSharingTrigger(){
        
        
        Test.startTest();
        
        User currUser = [SELECT Id FROM USER LIMIT 1 ];
        
        
		
        
        Test.stopTest();
        // Create a user
        // Create a contact
        // Link them up
        // Create a case w
    }
    
}